name = "KunQuestionMark"
uuid = "5841cb6e-ccde-49ef-aea9-fe176ba334c0"
authors = ["belathekun"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
